// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZy30ZrQXnosfDmWO7iB7iRlHbtdJ38Sg',
    appId: '1:860889378999:web:0622f14642154a55159d32',
    messagingSenderId: '860889378999',
    projectId: 'bicycle-project-98ae1',
    authDomain: 'bicycle-project-98ae1.firebaseapp.com',
    storageBucket: 'bicycle-project-98ae1.appspot.com',
    measurementId: 'G-0NYMGJEQFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9CsT0zlk8np85wtNmMTx4XSWc8TbJhko',
    appId: '1:860889378999:android:8c0543dfe8d78fc1159d32',
    messagingSenderId: '860889378999',
    projectId: 'bicycle-project-98ae1',
    storageBucket: 'bicycle-project-98ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-HKQRvxf98M5jtPVRdRgr9D5EVYvqJ4',
    appId: '1:860889378999:ios:4cd35ade432e7bc0159d32',
    messagingSenderId: '860889378999',
    projectId: 'bicycle-project-98ae1',
    storageBucket: 'bicycle-project-98ae1.appspot.com',
    iosClientId: '860889378999-dgbkh4f8rt894osa9ocs36tvdueeh7dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bicycleProjectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN-HKQRvxf98M5jtPVRdRgr9D5EVYvqJ4',
    appId: '1:860889378999:ios:4cd35ade432e7bc0159d32',
    messagingSenderId: '860889378999',
    projectId: 'bicycle-project-98ae1',
    storageBucket: 'bicycle-project-98ae1.appspot.com',
    iosClientId: '860889378999-dgbkh4f8rt894osa9ocs36tvdueeh7dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bicycleProjectApp',
  );
}
